export enum ClientStatusEnum {
  REGISTERED_CLIENT_ACTIVE = 'REGISTERED_CLIENT_ACTIVE',
  REGISTERED_CLIENT_NOT_ACTIVE = 'REGISTERED_CLIENT_NOT_ACTIVE',
  NOT_REGISTERED_CLIENT_ACTIVE = 'NOT_REGISTERED_CLIENT_ACTIVE',
  NOT_REGISTERED_CLIENT_NOT_ACTIVE = 'NOT_REGISTERED_CLIENT_NOT_ACTIVE',
  REGISTERED_NOT_CLIENT = 'REGISTERED_NOT_CLIENT',
  NOT_REGISTERED_NOT_CLIENT = 'NOT_REGISTERED_NOT_CLIENT',
}